### ISSUE TITLE
Типизация переменной

### ISSUE THREAD

**Issue by gearmobile** [i-hit/ajs-12.3#1]
https://github.com/i-hit/ajs-12.3/blob/d28ff9db29bb7ba2cfb418592da7d79ea38b7063/src/ts/service/Cart.ts#L88
TS позволяет не задавать явно тип переменной при ее инициализации, так как автоматически определит тип присваемой переменной и задаст этот тип для самой переменной

**Comment by gearmobile** [comment]
То есть, в Вашем случае более корректный вариант будет - `const result = this.getSum();`

**Comment by SemenovAndrei** [comment]
Спасибо, поправил.
